"""
Worker generico para melhoria de descricoes.
Uso: python melhorar_worker.py <api_key> <modelo> <arquivo1> [arquivo2] ...
Exemplo: python melhorar_worker.py gsk_xxx llama-3.1-8b-instant batch1 batch2
"""
import os, re, sys, json, time
from pathlib import Path

if sys.stdout.encoding != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    sys.stderr.reconfigure(encoding='utf-8', errors='replace')

from groq import Groq
import openpyxl
from openpyxl.utils import get_column_letter
from openpyxl.styles import Alignment

PASTA_OUTPUT   = Path(r"C:\Users\ctucunduva\fontes fuse\Claude Cowork - Image Search\Output Gemini Description")
CHECKPOINT_DIR = Path(r"C:\Users\ctucunduva\fontes fuse\Claude Cowork - Image Search")
CHECKPOINT_FILE = CHECKPOINT_DIR / "melhorar_descricoes_checkpoint.json"

DELAY_ENTRE_CHAMADAS = 8.0  # segundos entre chamadas (conservador)

PROMPT_SISTEMA = """You are an assistant that helps improve artwork descriptions for a museum website.
You will receive a description of an artwork generated by an AI that searched the internet.
Your task is to:
1. Rewrite the description removing any references to internet searches, such as phrases like:
   "I found on the internet", "my search revealed", "the search results show", "I searched online",
   "upon searching", "based on my internet search", "I was unable to find", "I could not find",
   "no references were found online", or similar expressions.
   The rewritten description should read as if it were written by an art expert — direct, confident, and informative.
   If the original text says the artwork was not found, write exactly: NOT_FOUND
2. Determine if the Gemini AI actually found real, specific information about the artwork (not generic or invented).
   Answer with one of: sim (found real references), nao (did not find / made up generic content), parcial (found some but incomplete).

Respond ONLY with a valid JSON object in this exact format:
{
  "analise_melhorada": "the improved description text here, or NOT_FOUND",
  "sucesso_revisado": "sim|nao|parcial"
}
Do not include any explanation outside the JSON."""

if len(sys.argv) < 4:
    print("Uso: python melhorar_worker.py <api_key> <modelo> <arquivo1> [arquivo2] ...")
    sys.exit(1)

API_KEY_GROQ = sys.argv[1]
MODELO       = sys.argv[2]
ARQUIVOS     = sys.argv[3:]

print(f"Worker: modelo={MODELO} | arquivos={ARQUIVOS} | key=...{API_KEY_GROQ[-6:]}")

client = Groq(api_key=API_KEY_GROQ)

def ler_checkpoint():
    if CHECKPOINT_FILE.exists():
        with open(CHECKPOINT_FILE, encoding='utf-8') as f:
            return json.load(f)
    return {}

def salvar_checkpoint(cp):
    # escrita atomica via arquivo temporario
    tmp = CHECKPOINT_FILE.with_suffix('.tmp')
    with open(tmp, 'w', encoding='utf-8') as f:
        json.dump(cp, f, ensure_ascii=False, indent=2)
    tmp.replace(CHECKPOINT_FILE)

def chamar_groq(analise, identificacao, tentativas=5):
    prompt_usuario = f"Artwork: {identificacao}\n\nDescription:\n{analise}"
    for tentativa in range(tentativas):
        try:
            resp = client.chat.completions.create(
                model=MODELO,
                messages=[
                    {"role": "system", "content": PROMPT_SISTEMA},
                    {"role": "user", "content": prompt_usuario},
                ],
                max_tokens=1024,
                temperature=0.2,
            )
            texto = resp.choices[0].message.content.strip()
            match = re.search(r'\{[\s\S]*\}', texto)
            if match:
                return json.loads(match.group())
            raise ValueError(f"JSON nao encontrado: {texto[:200]}")
        except Exception as e:
            msg = str(e)
            if '429' in msg:
                espera = 60 * (tentativa + 1)
                print(f"\n    [rate limit] aguardando {espera}s...", end=" ", flush=True)
                time.sleep(espera)
            elif tentativa < tentativas - 1:
                time.sleep(5)
            else:
                raise e

checkpoint = ler_checkpoint()
print(f"Checkpoint carregado: {len(checkpoint)} obras ja processadas\n")

total_processado = 0
total_pulado = 0
total_erro = 0

for nome_base in ARQUIVOS:
    json_path = PASTA_OUTPUT / f"{nome_base}.json"
    xlsx_path = PASTA_OUTPUT / f"{nome_base}.xlsx"

    print(f"\n{'='*60}")
    print(f"Processando: {nome_base} [{MODELO}]")
    print(f"{'='*60}")

    with open(json_path, encoding='utf-8') as f:
        data = json.load(f)

    for r in data:
        if r.get('status') != 'sucesso':
            r.setdefault('analise_melhorada', '')
            r.setdefault('sucesso_revisado', '')
            continue

        chave = r.get('identificacao', '')
        analise = r.get('analise') or ''

        # recarrega checkpoint para pegar entradas de outros workers
        checkpoint = ler_checkpoint()

        if chave in checkpoint:
            r['analise_melhorada'] = checkpoint[chave]['analise_melhorada']
            r['sucesso_revisado']  = checkpoint[chave]['sucesso_revisado']
            total_pulado += 1
            continue

        if not analise.strip():
            r['analise_melhorada'] = ''
            r['sucesso_revisado']  = 'nao'
            checkpoint[chave] = {'analise_melhorada': '', 'sucesso_revisado': 'nao'}
            salvar_checkpoint(checkpoint)
            continue

        print(f"  [{total_processado+total_pulado+1}] {chave[:65]}...", end=" ", flush=True)
        try:
            resultado = chamar_groq(analise, chave)
            r['analise_melhorada'] = resultado.get('analise_melhorada', analise)
            r['sucesso_revisado']  = resultado.get('sucesso_revisado', '')
            checkpoint[chave] = {
                'analise_melhorada': r['analise_melhorada'],
                'sucesso_revisado':  r['sucesso_revisado'],
            }
            print(f"OK [{r['sucesso_revisado']}]")
            total_processado += 1
            salvar_checkpoint(checkpoint)
            time.sleep(DELAY_ENTRE_CHAMADAS)
        except Exception as e:
            print(f"ERRO: {str(e)[:100]}")
            r['analise_melhorada'] = analise
            r['sucesso_revisado']  = 'erro'
            total_erro += 1

    # salva JSON
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"  JSON salvo: {json_path.name}")

    # atualiza XLSX
    wb = openpyxl.load_workbook(xlsx_path)
    ws = wb.active
    headers = {ws.cell(row=1, column=c).value: c for c in range(1, ws.max_column+1)}

    if 'analise_melhorada' not in headers:
        col = ws.max_column + 1
        ws.cell(row=1, column=col, value='analise_melhorada')
        ws.column_dimensions[get_column_letter(col)].width = 80
        headers['analise_melhorada'] = col

    if 'sucesso_revisado' not in headers:
        col = ws.max_column + 1
        ws.cell(row=1, column=col, value='sucesso_revisado')
        ws.column_dimensions[get_column_letter(col)].width = 18
        headers['sucesso_revisado'] = col

    col_id = headers.get('identificacao')
    id_para_linha = {}
    if col_id:
        for row in range(2, ws.max_row + 1):
            val = ws.cell(row=row, column=col_id).value
            if val:
                id_para_linha[val] = row

    col_am = headers['analise_melhorada']
    col_sr = headers['sucesso_revisado']
    for r in data:
        chave = r.get('identificacao', '')
        linha = id_para_linha.get(chave)
        if linha:
            cell_am = ws.cell(row=linha, column=col_am, value=r.get('analise_melhorada', ''))
            cell_am.alignment = Alignment(wrap_text=True)
            ws.cell(row=linha, column=col_sr, value=r.get('sucesso_revisado', ''))

    wb.save(xlsx_path)
    print(f"  XLSX salvo: {xlsx_path.name}")

print(f"\n{'='*60}")
print(f"WORKER CONCLUIDO [{MODELO}]")
print(f"  Processados: {total_processado} | Pulados: {total_pulado} | Erros: {total_erro}")
print(f"{'='*60}")
