import os, re, sys, json, time
from pathlib import Path
from datetime import datetime

if sys.stdout.encoding != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    sys.stderr.reconfigure(encoding='utf-8', errors='replace')

from groq import Groq
import openpyxl
from openpyxl.utils import get_column_letter
from openpyxl.styles import Alignment

API_KEY_GROQ   = "REMOVED"
PASTA_OUTPUT   = Path(r"C:\Users\ctucunduva\fontes fuse\Claude Cowork - Image Search\Output Gemini Description")
MODELO         = "llama-3.1-8b-instant"
CHECKPOINT_DIR = Path(r"C:\Users\ctucunduva\fontes fuse\Claude Cowork - Image Search")
ARQUIVOS       = ["batch1", "batch2", "batch3", "beta1"]

PROMPT_SISTEMA = """You are an assistant that helps improve artwork descriptions for a museum website.
You will receive a description of an artwork generated by an AI that searched the internet.
Your task is to:
1. Rewrite the description removing any references to internet searches, such as phrases like:
   "I found on the internet", "my search revealed", "the search results show", "I searched online",
   "upon searching", "based on my internet search", "I was unable to find", "I could not find",
   "no references were found online", or similar expressions.
   The rewritten description should read as if it were written by an art expert — direct, confident, and informative.
   If the original text says the artwork was not found, write exactly: NOT_FOUND
2. Determine if the Gemini AI actually found real, specific information about the artwork (not generic or invented).
   Answer with one of: sim (found real references), nao (did not find / made up generic content), parcial (found some but incomplete).

Respond ONLY with a valid JSON object in this exact format:
{
  "analise_melhorada": "the improved description text here, or NOT_FOUND",
  "sucesso_revisado": "sim|nao|parcial"
}
Do not include any explanation outside the JSON."""

FRASES_INTERNET = [
    'found on the internet', 'searched the internet', 'search the internet',
    'my search', 'the search results', 'i searched', 'based on my search',
    'according to my search', 'upon searching', 'after searching',
    'from my internet search', 'internet search', 'web search', 'online search',
    'i was unable to find', 'could not find', "couldn't find", 'i could not find',
    'no references', 'no specific information', 'no information was found',
    'no results', 'unable to locate',
]

def tem_referencia_internet(texto):
    t = (texto or '').lower()
    return any(f in t[:600] for f in FRASES_INTERNET)

client = Groq(api_key=API_KEY_GROQ)

DELAY_ENTRE_CHAMADAS = 5.0  # segundos entre chamadas (~12/min)

def chamar_groq(analise, identificacao, tentativas=5):
    prompt_usuario = f"Artwork: {identificacao}\n\nDescription:\n{analise}"
    for tentativa in range(tentativas):
        try:
            resp = client.chat.completions.create(
                model=MODELO,
                messages=[
                    {"role": "system", "content": PROMPT_SISTEMA},
                    {"role": "user", "content": prompt_usuario},
                ],
                max_tokens=1024,
                temperature=0.2,
            )
            texto = resp.choices[0].message.content.strip()
            match = re.search(r'\{[\s\S]*\}', texto)
            if match:
                return json.loads(match.group())
            raise ValueError(f"JSON nao encontrado na resposta: {texto[:200]}")
        except Exception as e:
            msg = str(e)
            if '429' in msg:
                espera = 60 * (tentativa + 1)  # 60s, 120s, 180s...
                print(f"\n    [rate limit] aguardando {espera}s...", end=" ", flush=True)
                time.sleep(espera)
            elif tentativa < tentativas - 1:
                time.sleep(5)
            else:
                raise e

# carrega checkpoint geral
CHECKPOINT_FILE = CHECKPOINT_DIR / "melhorar_descricoes_checkpoint.json"
checkpoint = {}
if CHECKPOINT_FILE.exists():
    with open(CHECKPOINT_FILE, encoding='utf-8') as f:
        checkpoint = json.load(f)
    print(f"Checkpoint carregado: {len(checkpoint)} obras ja processadas\n")

total_processado = 0
total_pulado = 0
total_erro = 0

for nome_base in ARQUIVOS:
    json_path  = PASTA_OUTPUT / f"{nome_base}.json"
    xlsx_path  = PASTA_OUTPUT / f"{nome_base}.xlsx"

    print(f"\n{'='*60}")
    print(f"Processando: {nome_base}")
    print(f"{'='*60}")

    # carrega JSON
    with open(json_path, encoding='utf-8') as f:
        data = json.load(f)

    # processa cada registro
    for r in data:
        if r.get('status') != 'sucesso':
            r.setdefault('analise_melhorada', '')
            r.setdefault('sucesso_revisado', '')
            continue

        chave = r.get('identificacao', '')
        analise = r.get('analise') or ''

        # ja processado no checkpoint?
        if chave in checkpoint:
            r['analise_melhorada'] = checkpoint[chave]['analise_melhorada']
            r['sucesso_revisado']  = checkpoint[chave]['sucesso_revisado']
            total_pulado += 1
            continue

        # sem analise
        if not analise.strip():
            r['analise_melhorada'] = ''
            r['sucesso_revisado']  = 'nao'
            checkpoint[chave] = {'analise_melhorada': '', 'sucesso_revisado': 'nao'}
            continue

        # chama groq
        print(f"  [{total_processado+total_pulado+1}] {chave[:65]}...", end=" ", flush=True)
        try:
            resultado = chamar_groq(analise, chave)
            r['analise_melhorada'] = resultado.get('analise_melhorada', analise)
            r['sucesso_revisado']  = resultado.get('sucesso_revisado', '')
            checkpoint[chave] = {
                'analise_melhorada': r['analise_melhorada'],
                'sucesso_revisado':  r['sucesso_revisado'],
            }
            print(f"OK [{r['sucesso_revisado']}]")
            total_processado += 1
            time.sleep(DELAY_ENTRE_CHAMADAS)
        except Exception as e:
            print(f"ERRO: {str(e)[:100]}")
            r['analise_melhorada'] = analise  # fallback: mantém original
            r['sucesso_revisado']  = 'erro'
            total_erro += 1

        # salva checkpoint a cada 10
        if (total_processado + total_erro) % 10 == 0:
            with open(CHECKPOINT_FILE, 'w', encoding='utf-8') as f:
                json.dump(checkpoint, f, ensure_ascii=False, indent=2)

    # salva JSON atualizado
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"  JSON salvo: {json_path.name}")

    # atualiza XLSX
    wb = openpyxl.load_workbook(xlsx_path)
    ws = wb.active

    # descobre colunas existentes
    headers = {ws.cell(row=1, column=c).value: c for c in range(1, ws.max_column+1)}

    # adiciona colunas novas se nao existirem
    if 'analise_melhorada' not in headers:
        col = ws.max_column + 1
        ws.cell(row=1, column=col, value='analise_melhorada')
        ws.column_dimensions[get_column_letter(col)].width = 80
        headers['analise_melhorada'] = col

    if 'sucesso_revisado' not in headers:
        col = ws.max_column + 1
        ws.cell(row=1, column=col, value='sucesso_revisado')
        ws.column_dimensions[get_column_letter(col)].width = 18
        headers['sucesso_revisado'] = col

    # mapeia identificacao -> linha
    col_id = headers.get('identificacao')
    id_para_linha = {}
    if col_id:
        for row in range(2, ws.max_row + 1):
            val = ws.cell(row=row, column=col_id).value
            if val:
                id_para_linha[val] = row

    # preenche valores
    col_am = headers['analise_melhorada']
    col_sr = headers['sucesso_revisado']
    for r in data:
        chave = r.get('identificacao', '')
        linha = id_para_linha.get(chave)
        if linha:
            cell_am = ws.cell(row=linha, column=col_am, value=r.get('analise_melhorada', ''))
            cell_am.alignment = Alignment(wrap_text=True)
            ws.cell(row=linha, column=col_sr, value=r.get('sucesso_revisado', ''))

    wb.save(xlsx_path)
    print(f"  XLSX salvo: {xlsx_path.name}")

# checkpoint final
with open(CHECKPOINT_FILE, 'w', encoding='utf-8') as f:
    json.dump(checkpoint, f, ensure_ascii=False, indent=2)

print(f"\n{'='*60}")
print(f"CONCLUIDO")
print(f"  Processados via Groq: {total_processado}")
print(f"  Reaproveitados (checkpoint): {total_pulado}")
print(f"  Erros: {total_erro}")
print(f"{'='*60}")
